export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FILTER_AUTHORS = "FILTER_AUTHORS";
export const FETCH_AUTHOR_DETAIL = "FETCH_AUTHOR_DETAIL";
export const SET_AUTHOR_LOADING = "SET_AUTHOR_LOADING";
export const POST_AUTHOR = "POST_AUTHOR";
export const POST_BOOK = "POST_BOOK";
export const SET_ERRORS = "SET_ERRORS";
